//ACTIONS
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const RESET_TRANSACTIONS = "RESET_TRANSACTTIONS";

//STORE
export const TRANSACTIONS = "transactions";
